$wallpaper = rgb(/home/eren/Pictures/wallpaper.jpg)
$background = rgb(121314)
$foreground = rgb(e3e2e3)
$color0 = rgb(39393a)
$color1 = rgb(94abb7)
$color2 = rgb(9bb1bd)
$color3 = rgb(a3b7c2)
$color4 = rgb(abbdc7)
$color5 = rgb(b2c3cc)
$color6 = rgb(bac9d1)
$color7 = rgb(c7c6c7)
$color8 = rgb(464747)
$color9 = rgb(a9c8db)
$color10 = rgb(b2cedf)
$color11 = rgb(bbd4e3)
$color12 = rgb(c4dae7)
$color13 = rgb(cddfea)
$color14 = rgb(d6e5ee)
$color15 = rgb(e3e2e3)

$primary = rgb(bac9d1)
$secondary = rgb(c0c8cd)
$tertiary = rgb(b4cad6)
$surface = rgb(121314)
$surface_bright = rgb(39393a)
$error = rgb(ff5945)
