#
# Autostart
#
# This file is used to autostart applications when Hyprland starts.

# Reference: https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent

exec = ~/.config/waybar/.exec
execr-once = hyprpaper & swaync & solaar -w hide & alacritty --daemon & clipse -listen & easyeffects --gapplication-service & corectrl --minimize-systray